version: 1
formatters:
  simple:
    format: "%(asctime)s - %(filename)s:%(lineno)d - %(levelname)s - %(message)s"
  file_brief:
    format: "[Copilot %(levelname)s] %(asctime)s - %(message)s"
  project_console_brief:
    class: plato_copilot.utils.log_utils.ColorFormatter
handlers:
  project_console:
    class : logging.StreamHandler
    formatter: project_console_brief
    stream  : ext://sys.stdout
  console:
    class : logging.StreamHandler
    formatter: simple
    level   : CRITICAL
    stream  : ext://sys.stdout
  file:
    class : logging.FileHandler
    formatter: file_brief
    filename: logs/debug.log
  error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: file_brief
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
  project:
    level: DEBUG
    handlers: [project_console, file, error]

root:
  level: FATAL
  handlers: [console, error]